### ISSUE TITLE
Compilation failure in checker-framework code since update to 3.43.0

### ISSUE THREAD

**Issue by pSub** [typetools/checker-framework#6664]
While trying to update from 3.42.0 to 3.43 my build breaks with a strage compilation error "in" the checker-framework code [(link to Github Action build).](https://github.com/red6/dmn-check/actions/runs/9439291955/job/25997243126?pr=290)

```
[ERROR] error: Error in AnnotatedTypeMirror.fromExpression(RegexAnnotatedTypeFactory, either.map(Arrays::asList)): Enclosing type not found: type: Object supertype: Either<A extends Object, B extends Object>
```

I cloudn't really figure out where the method `fromExpression` in the class `AnnotatedTypeMirror` is. However, at lease the class `AnnotatedTypeMirror` is from the source of the checkerframework.

I can try to create a minimal example that reproduces that error, if needed.

**Comment by mernst** [comment]
Thanks for getting in touch, and I'm sorry you are having trouble.

First, could you please try 3.44.0?  We fixed quite a number of obscure crashes, and it is possible that 3.44.0 does not crash for you.

If 3.44.0 still crashes for you, then we would appreciate a minimal example that crashes, so that we can fix it.

**Comment by pSub** [comment]
The error occurs with 3.44.0 as well, but the message is less specific:

```
error: Enclosing type not found: type: Object supertype: Either<A extends Object, B extends Object>
```

I will try to create a minimal example.

**Comment by pSub** [comment]
I think I have a small example that reproduces the error ([Java Code](https://github.com/pSub/reproduce-checker-framework-issue-6664/blob/main/validators/src/main/java/de/redsix/dmncheck/util/Either.java) and [Repository](https://github.com/pSub/reproduce-checker-framework-issue-6664)). I am using derive4j in this example and I am not sure whether this is a problem with the interaction between derive4j and checker-framework. Currently, I am unsure how to reproduce the error without derive4j.

**Comment by agentgt** [comment]
FWIW I'm having similar errors across my projects as the one 

* reported here 
* #6652 
* #6629 

I think I saw a different error in another project that I will add later.

It seems the culprit is the new type argument inference and I cannot figure out a way to suppress so we are stuck on 3.42.0.
