### ISSUE TITLE
Nullness Checker: NPE in BaseTypeVisitor 

### ISSUE THREAD

**Issue by GoogleCodeExporter** [typetools/checker-framework#102]
```
What steps will reproduce the problem?
1. create the sourcefile Bug.java with content

public final class Bug
{
  class C<T>
  {
  }

  void bug1()
  {
       C<String> c = new C<String>();
       m(c);
       m(c);      // note: the bug disapear if calling m only once
  }

  </*@checkers.nullness.quals.PolyNull*/ T> void m(final C</*@checkers.nullness.quals.PolyNull*/  String> a) {}
}

2. compile it with the checker framework (actual: javac 1.7.0-jsr308-1.1.5) :

  C:\jdk1.6.0_25\bin\java.exe -Xmx512m -Xbootclasspath/p:"C:\checkers\binary\jsr308-all.jar" -jar C:\checkers\binary\jsr308-all.jar -processor checkers.nullness.NullnessChecker -implicit:class -Awarns -d C:\classes -g -version -verbose -classpath C:\classes

What is the expected output? 

   should compile

What do you see instead?

javac 1.7.0-jsr308-1.1.5
[parsing started RegularFileObject[Bug.java]]
Round 1:
    input files: {Bug}
    annotations: []
    last round: false
Processor checkers.nullness.NullnessChecker matches [] and returns false.
Round 2:
    input files: {}
    annotations: []
    last round: true
java.lang.Error: NullnessSubchecker processor threw unexpected exception when 
processing Bug.java
    at checkers.source.SourceChecker.typeProcess(SourceChecker.java:301)
    at checkers.util.AggregateChecker.typeProcess(AggregateChecker.java:59)
    at com.sun.source.util.AbstractTypeProcessor$AttributionTaskListener.finished(AbstractTypeProcessor.java:212)
    at com.sun.source.util.AbstractTypeProcessor$TaskListeners.finished(AbstractTypeProcessor.java:260)
    at com.sun.source.util.AbstractTypeProcessor$TaskListeners.finished(AbstractTypeProcessor.java:260)
    at com.sun.source.util.AbstractTypeProcessor$TaskListeners.finished(AbstractTypeProcessor.java:260)
    at com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1268)
    at com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1227)
    at com.sun.tools.javac.main.JavaCompiler.compile2(JavaCompiler.java:881)
    at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:840)
    at com.sun.tools.javac.main.Main.compile(Main.java:417)
    at com.sun.tools.javac.main.Main.compile(Main.java:331)
    at com.sun.tools.javac.main.Main.compile(Main.java:322)
    at com.sun.tools.javac.Main.compile(Main.java:76)
    at com.sun.tools.javac.Main.main(Main.java:61)
    at checkers.util.CheckerMain.main(CheckerMain.java:39)
Caused by: java.lang.NullPointerException
    at checkers.basetype.BaseTypeVisitor.checkTypeArguments(BaseTypeVisitor.java:669)
    at checkers.basetype.BaseTypeVisitor.visitMethodInvocation(BaseTypeVisitor.java:299)
    at checkers.nullness.NullnessVisitor.visitMethodInvocation(NullnessVisitor.java:285)
    at checkers.nullness.NullnessVisitor.visitMethodInvocation(NullnessVisitor.java:49)
    at com.sun.tools.javac.tree.JCTree$JCMethodInvocation.accept(JCTree.java:1337)
    at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:67)
    at checkers.basetype.BaseTypeVisitor.scan(BaseTypeVisitor.java:122)
    at checkers.basetype.BaseTypeVisitor.scan(BaseTypeVisitor.java:73)
    at com.sun.source.util.TreeScanner.visitExpressionStatement(TreeScanner.java:241)
    at com.sun.tools.javac.tree.JCTree$JCExpressionStatement.accept(JCTree.java:1177)
    at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:67)
    at checkers.basetype.BaseTypeVisitor.scan(BaseTypeVisitor.java:122)
    at checkers.basetype.BaseTypeVisitor.scan(BaseTypeVisitor.java:73)
    at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:80)
    at com.sun.source.util.TreeScanner.scan(TreeScanner.java:90)
    at com.sun.source.util.TreeScanner.visitBlock(TreeScanner.java:160)
    at com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:794)
    at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:67)
    at checkers.basetype.BaseTypeVisitor.scan(BaseTypeVisitor.java:122)
    at checkers.basetype.BaseTypeVisitor.scan(BaseTypeVisitor.java:73)
    at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:80)
    at com.sun.source.util.TreeScanner.visitMethod(TreeScanner.java:143)
    at checkers.basetype.BaseTypeVisitor.visitMethod(BaseTypeVisitor.java:218)
    at checkers.nullness.NullnessVisitor.visitMethod(NullnessVisitor.java:266)
    at checkers.nullness.NullnessVisitor.visitMethod(NullnessVisitor.java:49)
    at com.sun.tools.javac.tree.JCTree$JCMethodDecl.accept(JCTree.java:694)
    at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:67)
    at checkers.basetype.BaseTypeVisitor.scan(BaseTypeVisitor.java:122)
    at checkers.basetype.BaseTypeVisitor.scan(BaseTypeVisitor.java:73)
    at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:80)
    at com.sun.source.util.TreeScanner.scan(TreeScanner.java:90)
    at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:98)
    at com.sun.source.util.TreeScanner.visitClass(TreeScanner.java:132)
    at checkers.basetype.BaseTypeVisitor.visitClass(BaseTypeVisitor.java:158)
    at checkers.basetype.BaseTypeVisitor.visitClass(BaseTypeVisitor.java:73)
    at com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:618)
    at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:49)
    at checkers.source.SourceChecker.typeProcess(SourceChecker.java:293)
    ... 15 more
An exception has occurred in the compiler (1.7.0-jsr308-1.1.5). Please report 
this bug so we can fix it.  For instructions, see 
http://types.cs.washington.edu/checker-framework/current/README-jsr308.html#repo
rting-bugs .  Thank you.
java.lang.Error: NullnessSubchecker processor threw unexpected exception when 
processing Bug.java
    at checkers.source.SourceChecker.typeProcess(SourceChecker.java:301)
    at checkers.util.AggregateChecker.typeProcess(AggregateChecker.java:59)
    at com.sun.source.util.AbstractTypeProcessor$AttributionTaskListener.finished(AbstractTypeProcessor.java:212)
    at com.sun.source.util.AbstractTypeProcessor$TaskListeners.finished(AbstractTypeProcessor.java:260)
    at com.sun.source.util.AbstractTypeProcessor$TaskListeners.finished(AbstractTypeProcessor.java:260)
    at com.sun.source.util.AbstractTypeProcessor$TaskListeners.finished(AbstractTypeProcessor.java:260)
    at com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1268)
    at com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1227)
    at com.sun.tools.javac.main.JavaCompiler.compile2(JavaCompiler.java:881)
    at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:840)
    at com.sun.tools.javac.main.Main.compile(Main.java:417)
    at com.sun.tools.javac.main.Main.compile(Main.java:331)
    at com.sun.tools.javac.main.Main.compile(Main.java:322)
    at com.sun.tools.javac.Main.compile(Main.java:76)
    at com.sun.tools.javac.Main.main(Main.java:61)
    at checkers.util.CheckerMain.main(CheckerMain.java:39)
Caused by: java.lang.NullPointerException
    at checkers.basetype.BaseTypeVisitor.checkTypeArguments(BaseTypeVisitor.java:669)
    at checkers.basetype.BaseTypeVisitor.visitMethodInvocation(BaseTypeVisitor.java:299)
    at checkers.nullness.NullnessVisitor.visitMethodInvocation(NullnessVisitor.java:285)
    at checkers.nullness.NullnessVisitor.visitMethodInvocation(NullnessVisitor.java:49)
    at com.sun.tools.javac.tree.JCTree$JCMethodInvocation.accept(JCTree.java:1337)
    at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:67)
    at checkers.basetype.BaseTypeVisitor.scan(BaseTypeVisitor.java:122)
    at checkers.basetype.BaseTypeVisitor.scan(BaseTypeVisitor.java:73)
    at com.sun.source.util.TreeScanner.visitExpressionStatement(TreeScanner.java:241)
    at com.sun.tools.javac.tree.JCTree$JCExpressionStatement.accept(JCTree.java:1177)
    at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:67)
    at checkers.basetype.BaseTypeVisitor.scan(BaseTypeVisitor.java:122)
    at checkers.basetype.BaseTypeVisitor.scan(BaseTypeVisitor.java:73)
    at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:80)
    at com.sun.source.util.TreeScanner.scan(TreeScanner.java:90)
    at com.sun.source.util.TreeScanner.visitBlock(TreeScanner.java:160)
    at com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:794)
    at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:67)
    at checkers.basetype.BaseTypeVisitor.scan(BaseTypeVisitor.java:122)
    at checkers.basetype.BaseTypeVisitor.scan(BaseTypeVisitor.java:73)
    at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:80)
    at com.sun.source.util.TreeScanner.visitMethod(TreeScanner.java:143)
    at checkers.basetype.BaseTypeVisitor.visitMethod(BaseTypeVisitor.java:218)
    at checkers.nullness.NullnessVisitor.visitMethod(NullnessVisitor.java:266)
    at checkers.nullness.NullnessVisitor.visitMethod(NullnessVisitor.java:49)
    at com.sun.tools.javac.tree.JCTree$JCMethodDecl.accept(JCTree.java:694)
    at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:67)
    at checkers.basetype.BaseTypeVisitor.scan(BaseTypeVisitor.java:122)
    at checkers.basetype.BaseTypeVisitor.scan(BaseTypeVisitor.java:73)
    at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:80)
    at com.sun.source.util.TreeScanner.scan(TreeScanner.java:90)
    at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:98)
    at com.sun.source.util.TreeScanner.visitClass(TreeScanner.java:132)
    at checkers.basetype.BaseTypeVisitor.visitClass(BaseTypeVisitor.java:158)
    at checkers.basetype.BaseTypeVisitor.visitClass(BaseTypeVisitor.java:73)
    at com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:618)
    at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:49)
    at checkers.source.SourceChecker.typeProcess(SourceChecker.java:293)
    ... 15 more
INTERNAL COMPILATION ERROR (exit code 4 but no recognized error messages)
Verbose output summary: 1 parsed sources, 0 loaded classes in project, 55 
loaded classes in cp.
                        0 wrote classes, 0 wrote inner classes. 

What version of the product are you using? On what operating system?

  (1.7.0-jsr308-1.1.5) on windows XP SP3.
   fails when using jdk 1.6.0_25 as launcher and also with 1.7.0

detailled java versions used:
 Java(TM) SE Runtime Environment (build 1.7.0-b147)
 Java HotSpot(TM) Client VM (build 21.0-b17, mixed mode)

 Java(TM) SE Runtime Environment (build 1.6.0_25-b06)
 Java HotSpot(TM) Client VM (build 20.0-b11, mixed mode, sharing)



Please provide any additional information below.


1) compiles well with 1.6.0_25 and 1.7.0
2) compiles well in absence of checkers 
3) fails with the NullnessChecker enabled
4) also fails when several polymorphic qualifiers are used in the  signature of 
m
5) the bug strangely disapears when calling m only once 


```

Original issue reported on code.google.com by `Stephan....@gmail.com` on 11 Aug 2011 at 7:33
