### PR TITLE
Add now passing test case.

### LINKED ISSUE #6739: Stream result after cast evaluated as having @PolyNull element
Compilation of

public class Test {

  public <T> Collection<T> clear(Class<T> type) {
    return Stream.of("abc")
        .map(type::cast)
        .toList();
  }
}

fails with

java: [return] incompatible types in return.
  type of expression: @Initialized @NonNull List<T extends @Initialized @PolyNull Object>
  method return type: @Initialized @NonNull Collection<T extends @Initialized @Nullable Object>

function with @PolyNull annotated return type should evaluate based on its argument type (e.g. @NonNull in this case)

Worked fine in 3.42.0, broken in 3.46.0

### PR DESCRIPTION
**Pull request by smillst**
Fixes #6739 .

### CODE REVIEW

**Comment by smillst** [comment]
Near mind.  I ran the wrong checker.
