### ISSUE TITLE
Many suspicious errors: [builder:required.method.not.known] after upgrade to 3.36.0

### ISSUE THREAD

**Issue by jacek-lewandowski** [typetools/checker-framework#6077]
I'm getting many those errors while the project was already compilable with 3.35.

For example, I had to do this to stop this error being reported:
https://github.com/apache/cassandra/pull/2370/commits/7b3c4ce8e5d6da41791492903ec367b8857cd57d#diff-234d3942bee540163239ada08e27e2aee864d00a3a5f356f570e18684d1bae03R167

It is weird because neither `Iterator` nor `PaxosKeyState` has any `@MustCall` obligations. I get that in many more places, yet I don't see any pattern.

Another example (which you can reproduce because I haven't fixed that yet: `ant cf-only -Dcf.check.only=org/apache/cassandra/index/sasi/conf/IndexMode.java`):

```
    [javac] /home/jlewandowski/dev/cassandra/c18239-static-analysis/src/java/org/apache/cassandra/index/sasi/conf/IndexMode.java:175: error: [builder:required.method.not.known] The checker cannot determine the must call methods of literalOption or any of its aliases, so it could not determine if they were called. Typically, this error indicates that you need to write an @MustCall annotation (often on an unconstrained generic type).
    [javac]             String literalOption = indexOptions.get(INDEX_IS_LITERAL_OPTION);
    [javac]                    ^
    [javac]   The type of object is: java.lang.String.
    [javac]   Reason for going out of scope: regular method exit
```

where `indexOptions` is a method parameter of type `Map<String, String>`.

**Comment by kelloggm** [comment]
These are caused by the soundness fix in #5912, which closed a (frankly pretty serious) bug related to how type variables are handled. We expected it to introduce a few false positives, but from your description it sounds like the impact is more serious than we'd anticipated. I'm sorry about that - I made a judgment call that the number of false positives would probably be worth fixing the soundness problem, but it sounds from your description that, at least in your case, that's not how it seemed.

I'll look into the specific examples that you cited (in `IndexMode.java` and the one you fixed in `PaxosUncommittedTracker.java`) and see if I can build small versions that I can use as test cases. If so, I might be able to improve these to avoid issuing too many of these errors.

**Comment by jacek-lewandowski** [comment]
thank you @kelloggm, I really appreciate that!

**Comment by msridhar** [comment]
@jacek-lewandowski could you possibly test the latest main branch of the Checker Framework on Cassandra to see if this issue if fixed, [by locally installing a SNAPSHOT version](https://checkerframework.org/manual/#maven-locally-built)?

**Comment by jacek-lewandowski** [comment]
sure, I'll try to do that today

**Comment by msridhar** [comment]
Thanks for testing!  This one looks trickier, so I am going to open it as a new issue and close this one.
