### PR TITLE
qualifiers is already null

### PR DESCRIPTION
**Pull request by gokaco**

### CODE REVIEW

File: framework/src/main/java/org/checkerframework/framework/util/defaults/QualifierDefaults.java [hunk 1]
```diff
@@ -588,9 +588,7 @@ private DefaultSet defaultsAt(final Element elt) {
         {
             AnnotationMirror ds = atypeFactory.getDeclAnnotation(elt, DefaultQualifiers.class);
             if (ds != null) {
-                if (qualifiers == null) {
-                    qualifiers = new DefaultSet();
-                }
+                qualifiers = new DefaultSet();
```
Comment (wmdietl) [inline framework/src/main/java/org/checkerframework/framework/util/defaults/QualifierDefaults.java]: `qualifiers` might already be initialized from line 579 above. This change would simply ignore those results.
However, we should discuss whether it ever makes sense to allow both a single `DefaultQualifier` and a `DefaultQualifiers` at the same time. However, we should then make that explicit and rewrite the code accordingly.

Comment (gokaco) [reply framework/src/main/java/org/checkerframework/framework/util/defaults/QualifierDefaults.java]: I was studying `DefaultQualifier` and `DefaultQualifiers` and I ran the given piece of code:-

import org.checkerframework.checker.nullness.qual.*;
import org.checkerframework.framework.qual.*;
import java.io.*;


@DefaultQualifier(value=Nullable.class,locations=TypeUseLocation.FIELD)
@DefaultQualifiers({@DefaultQualifier(value=NonNull.class,locations=TypeUseLocation.ALL)})
class ex
{
		Object nullableField = null;
    	`@NonNull `Object nonNullField = new Object();
    	void perl(Integer a)
    	{
    		a=null;
    	}
}
It was giving the output:-

.java:14: error: [assignment.type.incompatible] incompatible types in assignment.
    		a=null;
    		  ^
  found   : null
  required: @Initialized @NonNull Integer
1 error

But I think that it should give 2 errors.
Here if the proposed changes will be made then `@DefaultQualifiers` will work separately independent with this `@DefaultQualifier` and will give 2 errors:-
error: [assignment.type.incompatible] incompatible types in assignment.
		Object nullableField = null;
		                       ^
  found   : null
  required: @Initialized @NonNull Object
/home/kartik/Desktop/gsoc/ex.java:14: error: [assignment.type.incompatible] incompatible types in assignment.
    		a=null;
    		  ^
  found   : null
  required: @Initialized @NonNull Integer
2 errors

May In some cases this change would not be good. It totally depends on you whether you want this change or not. I made this PR to tell you about this thing. I should have created an issue rather than PR.

**Comment by mernst** [comment]
It seems that the underlying problem is a duplicate of #1307.  I think that fixing that might be a better solution.  Do you want to try that instead?

**Comment by gokaco** [comment]
> It seems that the underlying problem is a duplicate of #1307. I think that fixing that might be a better solution. Do you want to try that instead?

Ya, I can try. This will be a valuable feature in the software. You are right about that every declaration annotation that takes arguments should be repeatable. Will give you the updates asap.

**Comment by gokaco** [comment]
Mike, I am not understading the real motive of #1307 . @DefaultQualifier is repeatable using @DefaultQualifiers and @EnsureQualifierIf is also repeatable using @EnsuresQualifiersIf. Do you want that without @DefaultQualifiers and @EnsuresQualifiersIf they should be repeatable?

**Comment by mernst** [comment]
Please write discussion of #1307 at that issue, not here.

**Comment by wmdietl** [comment]
Work on this is continuing in #2369 so I'm closing this.
