### PR TITLE
Correct type argument inference for method references with var args.

### LINKED ISSUE #6664: Compilation failure in checker-framework code since update to 3.43.0
While trying to update from 3.42.0 to 3.43 my build breaks with a strage compilation error "in" the checker-framework code [(link to Github Action build).](https://github.com/red6/dmn-check/actions/runs/9439291955/job/25997243126?pr=290)

```
[ERROR] error: Error in AnnotatedTypeMirror.fromExpression(RegexAnnotatedTypeFactory, either.map(Arrays::asList)): Enclosing type not found: type: Object supertype: Either<A extends Object, B extends Object>
```

I cloudn't really figure out where the method `fromExpression` in the class `AnnotatedTypeMirror` is. However, at lease the class `AnnotatedTypeMirror` is from the source of the checkerframework.

I can try to create a minimal example that reproduces that error, if needed.

### PR DESCRIPTION
**Pull request by smillst**
Fixes #6664.

### CODE REVIEW

**Review by mernst — APPROVED** [review]
Thanks!
