### ISSUE TITLE
Handling of annotation defaulting in stubs between 3.4.0 and 3.4.1

### ISSUE THREAD

**Issue by cushon** [typetools/checker-framework#3597]
Prior to `3.4.0`, a stub file without annotations could be used to override annotations present in the corresponding classpath dependency (in the example below, the stub file for `p.B#f` has an implicitly non-null return type, which overrides the nullable type in the source file).

Was this change deliberate? The most likely culprit I see is https://github.com/typetools/checker-framework/commit/3ce0ab57300439da3646cdf5b93408440a048a2b. The repro doesn't use `-Ainfer`, and passing `-AmergeStubsWithSource` has no effect. If this change was deliberate, is there a way to restore the previous behaviour?

```
=== stubs/p.astub
package p;

import org.checkerframework.checker.nullness.qual.Nullable;

class B {
  Object f();
}
=== p/B.java
package p;

import org.checkerframework.checker.nullness.qual.Nullable;

class B {
  @Nullable
  Object f() {
    return new Object();
  }
}
=== p/A.java
package p;

class A {
  void f() {
    System.err.println(new B().f().toString());
  }
}
```

Compiling with `p.B` on the classpath, and with its corresponding stub, produces a diagnostic with `3.4.1` but not with `3.4.0`:

```
./checker-framework-3.4.0/checker/bin/javac p/B.java
./checker-framework-3.4.0/checker/bin/javac -Astubs=stubs -processor Nullness -sourcepath : -cp . p/A.java 
./checker-framework-3.4.1/checker/bin/javac -Astubs=stubs -processor Nullness -sourcepath : -cp . p/A.java 
p/A.java:5: error: [dereference.of.nullable] dereference of possibly-null reference new B().f()
    System.err.println(new B().f().toString());
                                ^
1 error
```

**Comment by kelloggm** [comment]
I've confirmed and reproduced this bug. There is a failing test case here: https://github.com/kelloggm/checker-framework/tree/stub-overwrite-bug

The bug is caused by 3ce0ab5, which I confirmed by running this test on that commit and the one before it. I'll look into the problem.

**Comment by kelloggm** [comment]
@cushon, thanks for finding this bug and building the test case. This led me to find a two related problems, which are all (hopefully) fixed (along with this one) in #3599.
