### ISSUE TITLE
private fields and flowexpr.parse.error

### ISSUE THREAD

**Issue by cushon** [typetools/checker-framework#1582]
Suppose we have

```java
package foo;

import org.checkerframework.checker.nullness.qual.EnsuresNonNullIf;
import org.checkerframework.checker.nullness.qual.Nullable;

public class Foo {

  @Nullable Object theObject;

  Foo(@Nullable Object theObject) {
    this.theObject = theObject;
  }

  @SuppressWarnings("contracts.conditional.postcondition.not.satisfied")
  @EnsuresNonNullIf(
    expression = {"theObject", "getTheObject()"},
    result = true
  )
  public boolean hasTheObject() {
    return theObject != null;
  }

  @Nullable
  public Object getTheObject() {
    return theObject;
  }
}
```

```java
package mainrepropkg;

import foo.Foo;

public class FlowExprParseError {

  public void printAThing(Foo foo) {
    if (foo.hasTheObject()) {
      System.out.println("Print false: " + foo.getTheObject().equals(new Object()));
    }
  }
}
```

private fields (like `Foo.theObject`) usually do not affect separate compilation. Bazel relies on that fact to optimize builds, and prunes private fields and methods from the classes that appear on the compile-time class path (see [1]). If `Foo` and `FlowExprParseError` are compiled separately, the version of `Foo` on `FlowExprParseError`'s classpath does not contain the field `theObject`, and the checker framework reports an error:

```
mainrepropkg/FlowExprParseError.java:8: error: [flowexpr.parse.error] cannot parse the expression 'theObject: identifier not found'
    if (foo.hasTheObject()) {
                        ^
1 error
```

It would be nice if the checker framework tolerated missing symbols referenced by `@EnsuresNonNullIf` annotations, provided the symbols were not accessed by the current compilation.

[1] https://github.com/bazelbuild/bazel/tree/80a34dc97799961201e6dce20fd58dd08022c032/third_party/ijar

**Comment by smillst** [comment]
>It would be nice if the checker framework tolerated missing symbols referenced by @EnsuresNonNullIf annotations, provided the symbols were not accessed by the current compilation.

The missing symbols should only cause parse errors at call sites to methods with postconditions, such as `@EnsuresNonNullIf`.  (At the declaration of a method with a postcondition, the symbol won't be missing.)

Pull request #1595 changes the error key for those parse errors for postconditions to `flowexpr.parse.postcondition.error`.  This way you can suppress all of them  using `-AsuppressWarnings=flowexpr.parse.postcondition.error`.

**Comment by cushon** [comment]
If a postcondition has suppressed parse errors, will the symbols that can be parsed still get checked?

**Comment by smillst** [comment]
At a call site, a postcondition isn't checked, it's used to refine the types of the expression.  If such a parse error is suppressed, the types of expressions that parse correctly will be refined.  So, the `Foo` class won't issue any warnings.

**Comment by cushon** [comment]
Great, thanks for the explanation!

**Comment by smillst** [comment]
Note that we changed the error key to `flowexpr.parse.error.postcondition`.  So to suppress these warnings use: `-AsuppressWarnings=flowexpr.parse.error.postcondition`
