### PR TITLE
Change the direct super type of Enums

### LINKED ISSUE #2156: Non-default annotations on enum constants
The Checker Framework forbids `@Untainted` on an enum constant.
Perhaps it forbids all non-default qualifiers on enum constants.

To reproduce, consider the following code:

```
import org.checkerframework.checker.tainting.qual.*;

enum SampleEnum {
    @Untainted FIRST,
    @Tainted SECOND;
}

class Issue2156 {
    void test() {
        requireUntainted(SampleEnum.FIRST);
        // :: error: assignment.type.incompatible
        requireUntainted(SampleEnum.SECOND);
    }

    void requireUntainted(@Untainted SampleEnum sEnum) {}
}
```

Running ```javac -processor tainting -g Issue2156.java``` yields this undesirable error:

```
Issue2156.java:9: error: [assignment.type.incompatible] incompatible types in assignment.
    @Untainted FIRST,
               ^
  found   : @Tainted SampleEnum
  required: @Untainted SampleEnum
```

This test case is committed as `checker/tests/tainting/Issue2156.java`.

### LINKED ISSUE #6110: Question: how to create `EnumSet` from enum constant with non-default annotation
My apologies if this is already covered in the manual or another issue; I couldn't find it.  Consider the following example:
```java
import org.checkerframework.checker.tainting.qual.*;
import java.util.EnumSet;
class Test {
  @SuppressWarnings("assignment") // #2156 
  static enum TestEnum { ONE, @Untainted TWO }
  static void test() {
      EnumSet<@Tainted TestEnum> s1 = EnumSet.of(TestEnum.ONE);
      EnumSet<@Untainted TestEnum> s2 = EnumSet.of(TestEnum.TWO);
  }
}
```
After suppressing the warning caused by #2156, we get two more warnings on the assignment to `s2`:
```
/tmp/Test.java:10: error: [type.argument] incompatible type argument for type parameter E of EnumSet.
      EnumSet<@Untainted TestEnum> s2 = EnumSet.of(TestEnum.TWO);
              ^
  found   : @Untainted TestEnum
  required: @Tainted Enum<@Untainted TestEnum>
/tmp/Test.java:10: error: [type.argument] incompatible type argument for type parameter E extends @Tainted Enum<@Untainted TestEnum> of EnumSet.of.
      EnumSet<@Untainted TestEnum> s2 = EnumSet.of(TestEnum.TWO);
                                                  ^
  found   : @Untainted TestEnum
  required: @Tainted Enum<@Untainted TestEnum>
2 errors
```
Is there some way to annotate the assignment to `s2` to make it pass the checker?

### PR DESCRIPTION
**Pull request by smillst**
Make it so that a direct super type of a use of an enum, `@A MyEnum` is `@A Enum<@A MyEnum>`.  For example:
```
 enum TestEnum {
    ONE,
    @Untainted TWO
  }
```
`@Untainted TestEnum <: @Untainted Enum<@Untainted MyEnum>` and `@Tainted TestEnum <: @Tainted Enum<@Tainted MyEnum>`. Because `Enum` is [marked as covariant](https://github.com/typetools/jdk/pull/176), `@Untainted Enum<@Untainted MyEnum> <:  @Tainted Enum<@Tainted MyEnum>`

This pull request also adds a new error message for enum constant declarations so that the warning is less confusing.

Merge with https://github.com/typetools/jdk/pull/176.
Fixes #6110 and fixes #2156.

### CODE REVIEW

**Review by mernst — APPROVED** [review]
Thanks!
